### PR TITLE
Feature Improvement Set 1

### PR DESCRIPTION
**Pull request by RealSourceOfficial**
Added both camera tooltips and increased default link spacing to increase readability.

### CODE REVIEW

**Comment by kctekn** [comment]
Hi Source,

Thank you for your work on this!

Regarding the link distance, I believe a value of 17 might work better. Additionally, I noticed that the tooltips are quite difficult to see. Could we lighten the three blocks a bit? It’s hard to gauge if the visibility issue is the same on your end. And also, maybe we'll need a method to let user can turn it off when they will be finally familar with the operation.

Thanks again for your efforts!

**Comment by RealSourceOfficial** [comment]
Just for clarification, what do you mean by lightening the blocks? The background color or the text itself? Here's a preview from my end (I've already begun work on the minimize feature.)
image

**Comment by kctekn** [comment]
Here is the preview from my end, I can hardly to see it
image
This is from another minimal setup obsidian:
image
BTW: I'm on a desktop. Hope this informaiton will help.

**Comment by RealSourceOfficial** [comment]
Interesting, the font color doesn't seem to be applying. If you go into the developer console and find the styles for the tooltip container, what's there? It renders white on my end, but maybe it's a weird issue with default font colors across platforms. 

Also do you have any idea how CSS animations work? I've used them before but for some reason I seem to be missing something - here's screenshots of what I have 
image
image

**Comment by kctekn** [comment]
image
The css style seems have been applied, but I'm not sure what is the foreground color.
For the css animation, I have no idea as I haven't used them before.

**Comment by RealSourceOfficial** [comment]
I'm currently trying to get help on the developer discord, but it's slow as usual, so it might be a while until I can get that fixed. For now it's permanent, as I think obsidian is truncating the animation on compilation.

**Comment by kctekn** [comment]
I still can't see it, but if change color in developer console like this:
image
It will show:
image
Think this would be OK because it looks the same as obsidian's tooltips:
image

**Comment by kctekn** [comment]
Awesome! It works well in both dark and light themes. I checked that the previous version actully worked in dark mode. Thanks again for your work. I'll merge it in now.

**Pull request merged**
